version: "3.9"

services:
    rpc:
        image: node:12
        command: bash -c "npm install && npx truffle develop"
        working_dir: /app
        volumes:
            - ./contracts:/app
        ports:
            - 9545:9545

    api:
        image: node:12
        command: bash -c "npm install && npm run dev"
        working_dir: /app
        volumes:
            - ./api:/app
            - ./storage:/app/storage
        ports:
            - 4000:4000
        environment:
            ETHER_RPC: http://rpc:9545
            MONGO_URI: mongodb://mongo:27017
            NFT_STORAGE_KEY: ${NFT_STORAGE_KEY}
            ETHER_CONTRACT: ${CONTRACT_ADDRESS}

    app:
        image: node:12
        command: bash -c "npm install && npm start"
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - 3000:3000
        environment:
            PROXY: http://api:4000

    mongo:
        image: mongo:4.4
        ports:
            - 27017:27017